name: langchain-snowpoc-docs
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - conda-forge
dependencies:
  - python=3.10
  - pikepdf=9.0.0
  - onnx=1.16.0
  - unstructured=0.14.9
  - beautifulsoup4=4.12.3
  - jupyterlab=4.1.5
  - ipywidgets=8.1.2
  - pyarrow=15.0.2
  - python-dotenv=1.0.1
  - tiktoken=0.6.0
  - transformers=4.39.3
  - requests=2.32.3
  - pip
  - pip:
    - unstructured[pdf]==0.14.9
    - langchain-community==0.2.6
    - langchain-core==0.2.10
    - langchain-text-splitters==0.2.2
    - langchain==0.2.6
    - snowflake-connector-python==3.7.1
    - snowflake-ml-python==1.3.0
    - snowflake-snowpark-python==1.13.0
    - streamlit==1.32.2
    - -r requirements.txt
